version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: rate-limiter-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  app:
    build: .
    container_name: rate-limiter-app
    ports:
      - "3000:3000"
    depends_on:
      - redis
    env_file:
      - .env
    restart: unless-stopped
